### ISSUE TITLE
Getting "underlying connection was closed" through SDK, works in postman

### ISSUE THREAD

**Issue by mikebz** [EllieMae/developerconnect-dotnet-bindings#11]
We have simple unit test that just works with webhook URL.  The test started failing last week.  It's failing on token generation.

Test Name:	WebhookEmptyCurrentHook
Test FullName:	Wholesale.Tests.EnCompassWebHookTest.WebhookEmptyCurrentHook
Test Source:	C:\Users\mborozdin\src\Ethos\MortgageWeb\MortgageWeb\Wholesale.Tests\EnCompassWebHookTest.cs : line 34
Test Outcome:	Failed
Test Duration:	0:00:00.4207491

```
Result StackTrace:	
at Elli.Api.OAuth.Api.TokenApi.GenerateTokenWithHttpInfo(String grantType, String username, String password, String scope, String redirectUri, String code, String session)
   at Elli.Api.Base.AccessToken.GetAccessToken(UserCredential credentials, String apiClientId, String clientSecret)
   at Mortgage.Wholesale.Util.EncompassWebHook.EncompassWebHookHelper.Init(WebHookConfig config) in C:\Users\mborozdin\src\Ethos\MortgageWeb\MortgageWeb\Wholesale\Util\EncompassWebHook\EncompassWebHookHelper.cs:line 76
   at Wholesale.Tests.EnCompassWebHookTest.Initialize() in C:\Users\mborozdin\src\Ethos\MortgageWeb\MortgageWeb\Wholesale.Tests\EnCompassWebHookTest.cs:line 29
Result Message:	Initialization method Wholesale.Tests.EnCompassWebHookTest.Initialize threw exception. Elli.Api.OAuth.Client.ApiException: Elli.Api.OAuth.Client.ApiException: Error calling GenerateToken: The underlying connection was closed: An unexpected error occurred on a send..
```

Has something changed?

**Comment by TylerBrinkley** [comment]
Ellie Mae is now requiring TLS 1.2 to connect to the API's so if your app is running under a .NET Framework version below 4.6 then you'll need to explicitly enable support for it by specifying the following in your code.

`ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;`
